# image with both python & nodejs installed
image: nikolaik/python-nodejs:python3.12-nodejs20-alpine

workflow:
  rules:
  # run pipeline automatically triggered by changes being pushed to project-branch
  - if: $CI_COMMIT_BRANCH == "project"
    when: always

stages:
- build
- test
- deploy

lint-and-build:
  stage: build
  script:
  # install dependencies
  - cd monitor && npm ci --prefer-offline && cd ..
  - cd service1 && npm ci --prefer-offline && cd ..
  - cd api-gateway && npm ci --prefer-offline && cd ..
  - pip install --no-cache-dir python-dotenv pika black pylint
  # format-check, lint, and build (when applicable) services
  - cd monitor && npm run lint && npm run build && cd ..
  - cd service1 && npm run lint && npm run build && cd ..
  - cd service2
  - find . -type f -name "*.py" | xargs python3 -m black --check
  - find . -type f -name "*.py" | xargs python3 -m pylint --errors-only
  - cd ..

unit-tests:
  stage: test
  services:
  - rabbitmq:3.10
  variables:
    NODE_ENV: "docker"
    RABBITMQ_PORT: 5672
    MONITOR_PORT: 0
    MONITOR_NAME: "monitor"
    API_GATEWAY_PORT: 0
    RABBITMQ_NAME: "rabbitmq"
    RABBITMQ_USER: "guest"
    RABBITMQ_PASS: "guest"
    RABBITMQ_TOPIC_LOG: "log"
    RABBITMQ_TOPIC_STATE_MONITOR: "state-monitor"
    RABBITMQ_TOPIC_STATE_SERVICE1: "state-service1"
    RABBITMQ_TOPIC_STATE_SERVICE2: "state-service2"
  script:
  # install dependencies
  - cd monitor && npm ci --prefer-offline && cd ..
  - cd api-gateway && npm ci --prefer-offline && cd ..
  # run tests
  - cd monitor && npm run test:ci && cd ..
  - cd api-gateway && npm run test:ci && cd ..

# deploy application to same machine where the GitLab runner runs
docker-deploy:
  stage: deploy
  image: docker:latest
  services:
  - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  script:
  - docker-compose up -d --build
